---
title: "MotoGP 2022 season finale"
subtitle: "Francesco Bagnaia vs Fabio Quartararo"
author: "Antonio Buzzelli"
date: "2022-10-09"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE, echo=FALSE}
library(readr)
library(tidyverse)
library(cowplot)
library(mosaic)

S2022 <- read_csv("../data/csv/2022.csv")
peccofabio <- S2022 %>% filter(rider.full_name %in% c("Francesco Bagnaia", "Fabio Quartararo"))
pecco <- S2022 %>% filter(rider.full_name == "Francesco Bagnaia")
fabio <- S2022 %>% filter(rider.full_name == "Fabio Quartararo")
peccofabio$event_name <- factor(peccofabio$event_name, order = TRUE, 
                                levels = unique(peccofabio$event_name))
```

# Comparison of positions and points {.tabset .tabset-fade .tabset-pills}

## Positions

```{r warning=FALSE}
plot_positions_density <- ggplot(peccofabio, aes(x=position, color=rider.full_name)) +
  geom_density(size = 1) +
  scale_color_manual(name = "Riders", values=c("blue", "red")) +
  ggtitle("Positions distribution")

plot_positions_bar <- ggplot(peccofabio, aes(x=factor(position), fill=rider.full_name)) +
  geom_bar(position = 'dodge') +
  scale_fill_manual(name = "Riders", values=c("blue", "red")) +
  scale_x_discrete(name = "Positions") +
  ylab("n") +
  ggtitle("Positions")

plot_grid(plot_positions_bar, plot_positions_density, nrow=2)
```
```{r warning=FALSE}
ggplot(peccofabio, aes(x = event_name, y = position, fill=rider.full_name)) +
  geom_col(position = 'dodge') +
  scale_fill_manual(name = "Riders", values=c("blue", "red")) +
  ggtitle("Positions at each event")
```

## Points

```{r warning=FALSE}
plot_points_density <- ggplot(peccofabio, aes(x=points, color=rider.full_name)) +
  geom_density(size = 1) +
  scale_color_manual(name = "Riders", values=c("blue", "red")) +
  ggtitle("Points distribution")

plot_points_bar <- ggplot(peccofabio, aes(x=factor(points), fill=rider.full_name)) +
  geom_bar(position = 'dodge') +
  scale_fill_manual(name = "Riders", values=c("blue", "red")) +
  scale_x_discrete(name = "Points") +
  ylab("n") +
  ggtitle("Points")

plot_grid(plot_points_density, plot_points_bar, nrow=2)
```
```{r warning=FALSE}
ggplot(peccofabio, aes(x = event_name, y = factor(points), fill=rider.full_name)) +
  geom_col(position = 'dodge') +
  scale_fill_manual(name = "Riders", values=c("blue", "red")) +
  ggtitle("Points at each event") +
  scale_y_discrete(name = "Points")
```

# Probability of winning the next race

## Francesco Bagnaia

```{r}
# probability distribution
n_races = nrow(pecco)

pts_prob_pecco <- pecco %>% 
  group_by(points) %>% 
  summarise(
    n = n(),
    p = n / n_races
  ) %>% 
  ungroup()

pts_prob_pecco[is.na(pts_prob_pecco)] <- 0
```




## Fabio Quartararo

```{r}
n_races = nrow(fabio)

pts_prob_fabio <- fabio %>% 
  group_by(points) %>% 
  summarise(
    n = n(),
    p = n / n_races
  ) %>% 
  ungroup()

pts_prob_fabio[is.na(pts_prob_fabio)] <- 0
```


